CREATE TABLE xlys.graphql_book(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR2(50) NOT NULL,
   page_count NUMBER NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE xlys.graphql_author(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(50) NOT NULL,
  last_name VARCHAR2(50) NOT NULL,
  book_id NUMBER NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (book_id) REFERENCES graphql_book(id)
);

CREATE TABLE xlys.graphql_hobby(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(50) NOT NULL,
  author_id NUMBER NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (author_id) REFERENCES xlys.graphql_author(id)
);